services:
  backend:
    build: .
    container_name: backend_petjoyful
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/petjoyful
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: mongo_petjoyful
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
