

services:
  mongodb:
    image: mongo:7
    container_name: pet-joyful-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pet-joyful-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: pet-joyful-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://admin:123456@mongodb:27017/PETJOYFUL-DB?authSource=admin
      LOGTAIL_TOKEN: ${LOGTAIL_TOKEN}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - pet-joyful-network

  frontend:
    container_name: pet-joyful-frontend
    build:
      context: /mnt/c/Users/João/OneDrive/Área de Trabalho/frontend-pet/Pet-Joyful---Projeto-Integrador--NextJs
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
    depends_on:
      - backend
    networks:
      - pet-joyful-network

volumes:
  mongo_data:

networks:
  pet-joyful-network:
    driver: bridge